### ISSUE TITLE
Suggestion: Add new category for non Zig projects.

### ISSUE THREAD

**Issue by kassane** [catdevnull/awesome-zig#30]
With `build.zig` it is common to have C or C++ projects using `zig cc` and `zig c++`.
Now with zig-pkg (0.11.0-dev) there will be even more C and C++ libraries.

e.g.:

**C**

- https://github.com/andrewrk/SDL
- https://github.com/andrewrk/ffmpeg
- https://github.com/andrewrk/libgroove
- https://github.com/andrewrk/libsoundio/tree/zig-pkg
- https://github.com/kassane/openssl
- https://github.com/kassane/libbpf
- https://github.com/kassane/winpthreads-zigbuild

**C++**

- https://github.com/andrewrk/libchromaprint
- https://github.com/kassane/asio
- https://github.com/kassane/fmt
- https://github.com/kassane/hana
- https://github.com/kassane/catch2
- https://github.com/kassane/outcome
- https://github.com/kassane/json (jsoncpp)
- https://github.com/kassane/range-v3
- https://github.com/kassane/libzmq

**Comment by catdevnull** [comment]
So, the idea would be to have a section for C/C++ libraries packaged for Zig, right?

**Comment by catdevnull** [comment]
what do you think of https://github.com/catdevnull/awesome-zig/pull/32?
